version: '2'
services:
  selenium:
    image: elgalu/selenium
    ports:
      - 4444:24444
      - 5900:25900
    env_file: .env.tz
    shm_size: 1g

  jenkins-php:
    image: dvmedvedev/jenkins-php-codeception
    ports:
      - 8080:8080
    env_file: .env.tz
    links:
      - selenium

  minions:
    build: .
    volumes:
      - ./app/:/home/minions/app:rw
      - /home/minions/app/node_modules
    env_file:
      - .env.tz
      - .env.minions
    links:
      - jenkins-php
