version: '2'
services:
  selenium:
    image: elgalu/selenium
    ports:
      - 4444:24444
      - 5900:25900
    shm_size: 1g

  jenkins-php:
    image: mesh1neko/jenkins-php:1.0
    ports:
      - 8080:8080
    links:
      - selenium

  minions:
    build: .
    volumes:
      - ./app/:/home/minions/app:rw
    env_file: .env
    links:
      - jenkins-php
